version: '2.1'

orbs:
  node: circleci/node@x.y

jobs:
  install-node:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
        node-version: '16.13'
      - run: node --version

workflows:
  node_test:
    jobs:
      - install-node
