version: '2.1'

jobs:
  deploy-cloudflare:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: wrangler-version
          command: 'wrangler --version'
  setup-node:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: node --version
      - run:
          name: install-dependencies
          command: "npm install"
      - run:
          name: install-chloudflare-CLI
          command: "npm install wrangler"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  node_test:
    jobs:
      - deploy-cloudflare:
        requires:
          - setup-node
