version: '2.1'

orbs:
  node: circleci/node@5.0.2

jobs:
  cloudflare-deploy:
    working_directory: ~/repo
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: 'build www'
          command: 'npm run build'
      - run:
          name: 'deploy'
          command: 'npx wrangler publish www'

  install-node:
    working_directory: ~/repo
    executor: node/default
    steps:
      - checkout
      - run: node --version
      - run:
          name: install-dependencies
          command: "npm install"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  node_test:
    jobs:
      - install-node
      - cloudflare-deploy:
          context:
            - CF_ACCOUNT_ID
          requires:
            - install-node
