version: 2.1

workflows:
  deploy:
    jobs:
      - build_node

jobs:
  build_node:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - run:
        name: install-dependencies
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
          - ./node_modules
