
version: 2.1
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build_ionic
      - build_android:
          requires:
            - build_ionic
orbs:
  android: circleci/android@2.1.2
jobs:
  build_ionic:
    working_directory: ~/repo
    docker:
      - image: cimg/node:19.0
    steps:
      - checkout
      - run:
          name: view files
          command: ls ~/repo/android
  build_android:
      working_directory: ~/repo
      docker:
        - image: cimg/android:2022.09-node
      steps:
        - checkout
        - run:
            name: update-npm
            command: "sudo npm install -g npm@8.19"
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: install-packages
            command: npm install
        - run:
            name: install ionic cli
            command: "sudo npm install -g @ionic/cli"
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
              - ./node_modules
        - run:
            name: build
            command: ionic build --prod
        - run:
            name: sync capacitor
            command: npx cap sync
        - run:
            name: build android
            command: ionic capacitor build android
        - run:
            name: view files
            command: ls ~/repo/android
        - run:
            name: install ruby
            command: sudo apt-get install ruby-full
        - run:
            name: install fastlane
            command: |
              sudo gem install fastlane -NV
              fastlane -v
        - run:
            name: install depedencies
            path: android
            command: |
              ./gradlew androidDependencies --debug
        - run:
            name: build fastlane android
            path: android
            command: |
              fastlane beta
        - store_artifacts:
            path: android/app/build/outputs/bundle
# build_firebase:
#      docker:
#       - image: cimg/node:12.16
#     working_directory: ~/repo
#     steps:
#       - checkout
#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#             - v1-dependencies-{{ checksum "package.json" }}
#             - v1-dependencies-
#       - run:
#           name: Install Dependencies
#           command: npm install
#       - run:
#           name: Build Application
#           command: npm run build
#       - save_cache:
#           key: v1-npm-deps-{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: Deploy to Firebase
#           command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
