version: '2.1'

jobs:
  install-node:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run: node --version
      - run:
          name: install-dependencies
          command: "npm install"

workflows:
  node_test:
    jobs:
      - install-node
