version: '2.1'

orbs:
  node: circleci/node@5.0.2

jobs:
  cloudflare-deploy:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: 'build www'
          command: 'npm run build'
      - run:
          name: 'deploy'
          command: 'npx wrangler --version'

  install-node:
    executor: node/default
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install NPM
          command: "sudo npm install -g npm@8.19"
      - run:
          name: install-dependencies
          command: "npm install"
      - run:
          name: install ionic cli
          command: "sudo npm install -g @ionic/cli"
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  node_test:
    jobs:
      - install-node
      - cloudflare-deploy:
          requires:
            - install-node
